export const browserCoreExamples = [
  "clawser status",
  "clawser start",
  "clawser stop",
  "clawser tabs",
  "clawser open https://example.com",
  "clawser focus abcd1234",
  "clawser close abcd1234",
  "clawser screenshot",
  "clawser screenshot --full-page",
  "clawser screenshot --ref 12",
  "clawser snapshot",
  "clawser snapshot --format aria --limit 200",
  "clawser snapshot --efficient",
  "clawser snapshot --labels",
];

export const browserActionExamples = [
  "clawser navigate https://example.com",
  "clawser resize 1280 720",
  "clawser click 12 --double",
  'clawser type 23 "hello" --submit',
  "clawser press Enter",
  "clawser hover 44",
  "clawser drag 10 11",
  "clawser select 9 OptionA OptionB",
  "clawser upload /tmp/clawser/uploads/file.pdf",
  'clawser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "clawser dialog --accept",
  'clawser wait --text "Done"',
  "clawser evaluate --fn '(el) => el.textContent' --ref 7",
  "clawser console --level error",
  "clawser pdf",
];
